# Generated by Django 5.0.6 on 2024-06-13 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompuestoGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Compuestos Genericos',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Marcas Comerciales',
            },
        ),
        migrations.CreateModel(
            name='PresentacionMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Presentacion del medicamento',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosificacion', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField(null=True)),
                ('compuesto_generico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.compuestogenerico')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.laboratorio')),
                ('marca_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.marcacomercial')),
                ('presentacion_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.presentacionmedicamento')),
            ],
        ),
    ]
