# Generated by Django 5.0.6 on 2024-06-13 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='StockProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Stock de proveedores',
            },
        ),
    ]
